# Aerospace is what is up

# Mouse follows focus when focused monitor changes
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

start-at-login = true

after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe4CDC4C inactive_color=0xff414550 width=7.0',
    # same for sketchybar
    'exec-and-forget sketchybar',
    # scratches:
    'exec-and-forget aerospace-scratchpad move Logseq',
    'exec-and-forget aerospace-scratchpad move kitty',
    'exec-and-forget aerospace-scratchpad move ChatGPT',
    'exec-and-forget aerospace-scratchpad move Spotify'
]

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top = [{ monitor.'C34H89x' = 28 }, { monitor.'Built-in Retina Display' = 0 }, 100]
    outer.right =      10

[workspace-to-monitor-force-assignment]
    1 = ['C34H89x', '^Built-in Retina Display$']
    2 = ['C34H89x', '^Built-in Retina Display$']
    3 = ['^Built-in Retina Display$', 'C34H89x']
    4 = ['C34H89x', '^Built-in Retina Display$']
    5 = ['C34H89x', '^Built-in Retina Display$']
    6 = ['C34H89x', '^Built-in Retina Display$']

[mode.main.binding]
    # i3 wraps focus by default
    alt-h = 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    alt-j = 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    alt-k = 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    alt-l = 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'

    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-h = 'move left --boundaries all-monitors-outer-frame'
    alt-shift-l = 'move right --boundaries all-monitors-outer-frame'

    # move to other monitor
    cmd-alt-shift-h = 'move-node-to-monitor --focus-follows-window left'
    cmd-alt-shift-l = 'move-node-to-monitor --focus-follows-window right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
    alt-i = 'join-with right'
    alt-o = 'join-with left'

    alt-f = 'fullscreen'

    alt-w = 'layout v_accordion' # 'layout stacking' in i3
    alt-s = 'layout h_accordion' # 'layout tabbed' in i3. probably never needing
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    # move whole workspace to monitor
    cmd-alt-shift-1 = 'move-workspace-to-monitor ^built-in retina display$'
    cmd-alt-shift-2 = 'move-workspace-to-monitor C34H89x'

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'

    # more:
    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

    # scratchpad
    cmd-backslash = "exec-and-forget aerospace-scratchpad show Logseq"
    alt-enter = "exec-and-forget aerospace-scratchpad show kitty"
    alt-space = "exec-and-forget aerospace-scratchpad show ChatGPT"
    alt-p = "exec-and-forget aerospace-scratchpad show Spotify"

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

## callbacks:
[[on-window-detected]]
    if.app-id = 'com.1password.1password'
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'net.kovidgoyal.kitty'
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.preview'
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'us.zoom.xos'
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-name-regex-substring = 'cursor'
    check-further-callbacks = true
    run = ['move-node-to-workspace 1']

[[on-window-detected]]
    if.app-name-regex-substring = 'slack'
    check-further-callbacks = true
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-name-regex-substring = 'signal'
    check-further-callbacks = true
    run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
    if.app-name-regex-substring = 'spotify'
    check-further-callbacks = true
    run = ['layout floating', 'move-node-to-workspace 5']
