#!/usr/bin/env zsh

PLUGIN_DIR="$CONFIG_DIR/plugins"

# default colors and shit
sketchybar --bar position=top height=25 blur_radius=30 color=0x40000000

default=(
  padding_left=1
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=5
  label.padding_right=7
)
sketchybar --default "${default[@]}"

##### Right Items #####

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Left
sketchybar --add event aerospace_workspace_change

declare -A monitors

while IFS=" " read -r monitor_id display_id; do
  monitors["$monitor_id"]="$display_id"
done < <(aerospace list-monitors --format '%{monitor-id} %{monitor-appkit-nsscreen-screens-id}')

for monitor_id in "${monitors[@]}"; do
  for sid in $(aerospace list-workspaces --monitor $monitor_id); do
    if [ "$sid" = ".scratchpad" ]; then
        continue
    fi
    sketchybar --add item space.$sid left \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
            display=${monitors["$monitor_id"]}\
            background.color=0x44ffffff \
            background.corner_radius=5 \
            background.height=20 \
            background.drawing=off \
            label="$sid" \
            click_script="aerospace workspace $sid" \
            script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done
done

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
